# This file contains hand-written unsigned transactions for localnet with:
#
# - 3 established accounts for "Albert", "Bertha" and "Christel"
# - a bond from "Albert"'s established account to validator-0
#
# Note that 1 localnet user account "Daewon" is left as
# implicit account, so their tokens are kept in the accounts derived from their
# keys used in `balances.toml`.
#
# This file is used to produce `signed-transactions.toml` with
# the `sign-genesis-txs` command.

# Albert
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qquurf975axryz4sf0jmyxpknkxp4cs7g8e8ahhpw089u6j3q9dy6qssdhz"]

# Bertha
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qrg6qx72e0vqhg8plg20hv97g3p3q092gl88jlngkly0hpmca2h2we44uzw"]

# Christel
[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = ["tpknam1qp7r3et2usz538fxzkm69h3awr7t0kgk7h6528za7pk4g2jldk5dz0qjkhx"]

##########################################################################################

# Albert bonds to `validator-0`
[[bond]]
source = "tnam1qye83lg3ncsen8wjedgz27rxjktn0gcrc574p78e"
validator = "tnam1q9q3lph40w88cs5000k48thkw3f7s0m6mqrtfgss"
amount = "20000"
